# --- Единый конфигурационный файл netlify.toml ---

# Настройки функций
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Правило для эффективного кэширования статических ресурсов (CSS, JS, картинки)
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Заголовки для HTML страниц
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    X-Robots-Tag = "index, follow"

# Заголовки для CSS и JS файлов
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Заголовки для изображений
[[headers]]
  for = "/*.(jpg|jpeg|png|gif|webp|svg|ico)"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# --- Правила для редиректов ---
[[redirects]]
  from = "/:lang/:section/:slug/"
  to = "/:lang/:section/:slug"
  status = 301
  force = true

[[redirects]]
  from = "/:lang/"
  to = "/:lang"
  status = 301
  force = true

# --- Правила для MPA ---
[[redirects]]
  from = "/"
  to = "/.netlify/functions/render"
  status = 200
  force = true

[[redirects]]
  from = "/:lang/:section/:slug"
  to = "/.netlify/functions/render"
  status = 200
  force = true

[[redirects]]
  from = "/:section/:slug"
  to = "/.netlify/functions/render"
  status = 200
  force = true

[[redirects]]
  from = "/*.(css|js|png|jpg|jpeg|gif|svg|ico|webp|woff|woff2|ttf|eot)"
  to = "/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true